# Week 4 — Error Analysis

In [1]:
import pandas as pd
from pathlib import Path
import sys

# Find the project root from wherever the notebook is executed.
ROOT = Path.cwd().resolve()

while ROOT != ROOT.parent and not (ROOT / "Data").exists():
    ROOT = ROOT.parent

# Make project modules importable if needed later.
sys.path.insert(0, str(ROOT))

OUT = ROOT / "Data" / "processed" / "calculated"

print("Project root:", ROOT)
print("Error file:", OUT / "week4_error_cases.csv")

errors = pd.read_csv(OUT / "week4_error_cases.csv")
errors.head(20)

Project root: C:\Users\USER\SNLP_Project
Error file: C:\Users\USER\SNLP_Project\Data\processed\calculated\week4_error_cases.csv

,query,author_id,author_name,relevant,tfidf_rank,semantic_rank
0,natural language processing,https://openalex.org/A5008116509,David L. Waltz,1,1,8
1,natural language processing,https://openalex.org/A5009605043,Magdalena Luszczynska,1,5,6
2,natural language processing,https://openalex.org/A5015602781,Karen Livescu,1,8,4
3,natural language processing,https://openalex.org/A5018230694,Eric Brill,1,10,2
4,natural language processing,https://openalex.org/A5066987539,Bonnie Lynn Nash-Webber,1,3,10
5,natural language processing,https://openalex.org/A5090002679,James F. Allen,1,9,1
6,natural language processing,https://openalex.org/A5103085805,Timothy J. Baldwin,1,7,3
7,natural language processing,https://openalex.org/A5109208983,Roger C. Schank,1,2,9
8,machine learning,https://openalex.org/A5007489034,Ninghao Liu,1,2,6
9,machine learning,https://openalex.org/A5013963697,Yalın Baştanlar,1,6,4
10,machine learning,https://openalex.org/A5018711331,Pedro Domingos,1,4,8
11,machine learning,https://openalex.org/A5072191151,Mengnan Du,1,3,7
12,machine learning,https://openalex.org/A5074537073,Thomas G. Dietterich,1,8,1
13,machine learning,https://openalex.org/A5091012089,Mustafa Özuysal,1,7,5
14,transformer based text classification,https://openalex.org/A5008078679,Muna Sulieman Al-Hawawreh,0,1,10
15,transformer based text classification,https://openalex.org/A5021878400,Noam Shazeer,1,6,4
16,transformer based text classification,https://openalex.org/A5072898802,Martín Müller,1,2,9
17,transformer based text classification,https://openalex.org/A5076683869,Peter J. Liu,1,7,5
18,information retrieval,https://openalex.org/A5020310155,Jon George Rokne,1,7,2
19,information retrieval,https://openalex.org/A5066265052,Reda Alhajj,1,6,1

In [2]:
errors.sort_values(["query", "relevant", "tfidf_rank", "semantic_rank"]).head(30)

,query,author_id,author_name,relevant,tfidf_rank,semantic_rank
20,information retrieval,https://openalex.org/A5125635347,Jirong Wen,1,4,6
21,information retrieval,https://openalex.org/A5140985364,Tong Ruan,1,5,7
19,information retrieval,https://openalex.org/A5066265052,Reda Alhajj,1,6,1
18,information retrieval,https://openalex.org/A5020310155,Jon George Rokne,1,7,2
27,knowledge graphs,https://openalex.org/A5089615958,Feng Xia,1,2,6
22,knowledge graphs,https://openalex.org/A5004286514,Ciyuan Peng,1,3,7
25,knowledge graphs,https://openalex.org/A5059512471,Tianxing Wu,1,5,9
26,knowledge graphs,https://openalex.org/A5074737251,Eva Blomqvist,1,6,1
24,knowledge graphs,https://openalex.org/A5041698136,Claudio Gutiérrez,1,7,3
23,knowledge graphs,https://openalex.org/A5014287041,Juan Sequeda,1,8,4
8,machine learning,https://openalex.org/A5007489034,Ninghao Liu,1,2,6
11,machine learning,https://openalex.org/A5072191151,Mengnan Du,1,3,7
10,machine learning,https://openalex.org/A5018711331,Pedro Domingos,1,4,8
9,machine learning,https://openalex.org/A5013963697,Yalın Baştanlar,1,6,4
13,machine learning,https://openalex.org/A5091012089,Mustafa Özuysal,1,7,5
12,machine learning,https://openalex.org/A5074537073,Thomas G. Dietterich,1,8,1
0,natural language processing,https://openalex.org/A5008116509,David L. Waltz,1,1,8
7,natural language processing,https://openalex.org/A5109208983,Roger C. Schank,1,2,9
4,natural language processing,https://openalex.org/A5066987539,Bonnie Lynn Nash-Webber,1,3,10
1,natural language processing,https://openalex.org/A5009605043,Magdalena Luszczynska,1,5,6
6,natural language processing,https://openalex.org/A5103085805,Timothy J. Baldwin,1,7,3
2,natural language processing,https://openalex.org/A5015602781,Karen Livescu,1,8,4
5,natural language processing,https://openalex.org/A5090002679,James F. Allen,1,9,1
3,natural language processing,https://openalex.org/A5018230694,Eric Brill,1,10,2
14,transformer based text classification,https://openalex.org/A5008078679,Muna Sulieman Al-Hawawreh,0,1,10
16,transformer based text classification,https://openalex.org/A5072898802,Martín Müller,1,2,9
15,transformer based text classification,https://openalex.org/A5021878400,Noam Shazeer,1,6,4
17,transformer based text classification,https://openalex.org/A5076683869,Peter J. Liu,1,7,5